name: Test
on: [push]

jobs:

  unit_tests:
    runs-on:
      ubuntu-latest
    steps:
    - run "echo 'Running tests on: ${{ runner.os }}
    - run: "echo 'Repo: ${{ github.repository }}'"
    - run: "echo 'Branch: ${{ github.ref }}'"
    - run: apt-get update && apt-get install -y plantuml 


steps:
- name: Install pixi
  uses: prefix-dev/setup-pixi@v0.9.3
  with:
    pixi-version: v0.62.2 # good to pin this since pixi is not 1.0 yet!
- run: pixi run pytest




